services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - youtube-fetcher-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - youtube-fetcher-network

volumes:
  mongodb_data:

networks:
  youtube-fetcher-network:
    driver: bridge
